---
- name: Connect to cluster and list nodes
  hosts: local
  tasks:
    - name: Detect to-be-Removed APIs in all namespaces excluding ones starting with openshift and kube-
      include_role:
        name: redhatci.ocp.deprecated_api
      vars:
        deprecated_api_logs:
          path: "{{ playbook_dir }}"
      register: compatibility_map
